env:
  browser: true
  es2021: true
extends:
  - 'airbnb'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'prettier'
rules: {
  import/no-cycle: [ 2, { maxDepth: 1 } ],
  import/prefer-default-export: 0,
  import/extensions: 0,
  no-console: 0,
  react/prop-types: 'off',
  consistent-return: 0,
  '@typescript-eslint/interface-name-prefix': 'off',
  '@typescript-eslint/explicit-function-return-type': 'off',
  '@typescript-eslint/explicit-module-boundary-types': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
  'click-events-have-key-events': 'off',
  "react/react-in-jsx-scope": "off",
  'react/jsx-props-no-spreading': "off",
  "no-param-reassign": 0,
  'react/jsx-filename-extension': [ 2, { 'extensions': [ '.js', '.jsx', '.ts', '.tsx' ] } ],
  "react/function-component-definition": [
    2,
    {
      namedComponents: "arrow-function",
      unnamedComponents: "arrow-function",
    },
  ],
}
